# Generated by Django 5.2 on 2025-05-04 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(default='Genérica', max_length=50)),
                ('protocolo', models.CharField(default='rtsp', max_length=10)),
                ('usuario', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('direccion_ip', models.CharField(max_length=50)),
                ('puerto', models.IntegerField(default=554)),
                ('streaming_path', models.CharField(max_length=150)),
                ('channel', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConteoPersonas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('contador_ingreso', models.IntegerField(default=0)),
                ('contador_salida', models.IntegerField(default=0)),
                ('camara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conteo_api.camara')),
            ],
        ),
        migrations.AddField(
            model_name='camara',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='conteo_api.estado'),
        ),
        migrations.CreateModel(
            name='ModeloConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modelo', models.CharField(max_length=100)),
                ('url_model', models.CharField(max_length=250)),
                ('image_size', models.IntegerField()),
                ('stride', models.IntegerField()),
                ('device', models.CharField(max_length=20)),
                ('confidence_threshold', models.FloatField()),
                ('classes', models.CharField(max_length=100)),
                ('agnostic_nms', models.BooleanField(default=False)),
                ('distance_threshold', models.FloatField()),
                ('rtsp_url', models.CharField(max_length=250)),
                ('camara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conteo_api.camara')),
            ],
        ),
        migrations.CreateModel(
            name='ConteoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde_hora', models.TimeField()),
                ('hasta_hora', models.TimeField()),
                ('camara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conteo_api.camara')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='conteo_api.estado')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conteo_api.modeloconfig')),
            ],
        ),
        migrations.CreateModel(
            name='Poligono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_poligono', models.CharField(max_length=100, unique=True)),
                ('area_interes', models.CharField(max_length=50)),
                ('camara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conteo_api.camara')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='conteo_api.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Coordenada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('poligono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordenadas', to='conteo_api.poligono')),
            ],
        ),
        migrations.CreateModel(
            name='TrackingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_type', models.CharField(max_length=50)),
                ('distance_threshold', models.FloatField()),
                ('dwell_time_threshold', models.FloatField()),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conteo_api.modeloconfig')),
            ],
        ),
    ]
