# Generated by Django 5.2 on 2025-05-04 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conteo_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camara',
            name='channel',
        ),
    ]
