# Generated by Django 5.2 on 2025-05-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteo_api', '0002_remove_camara_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeloconfig',
            name='agnostic_nms',
        ),
        migrations.RemoveField(
            model_name='modeloconfig',
            name='camara',
        ),
        migrations.RemoveField(
            model_name='modeloconfig',
            name='distance_threshold',
        ),
        migrations.RemoveField(
            model_name='modeloconfig',
            name='rtsp_url',
        ),
        migrations.RemoveField(
            model_name='modeloconfig',
            name='url_model',
        ),
        migrations.RemoveField(
            model_name='trackingconfig',
            name='tracker_type',
        ),
        migrations.AddField(
            model_name='modeloconfig',
            name='iou',
            field=models.FloatField(default=0.7, help_text='IoU threshold para NMS'),
        ),
        migrations.AddField(
            model_name='modeloconfig',
            name='max_det',
            field=models.IntegerField(default=80, help_text='Máximo número de detecciones por imagen'),
        ),
        migrations.AddField(
            model_name='modeloconfig',
            name='modelo',
            field=models.CharField(choices=[('yolo11n.pt', 'YOLOv11 Nano'), ('yolo11s.pt', 'YOLOv11 Small'), ('yolo11m.pt', 'YOLOv11 Medium'), ('yolo11l.pt', 'YOLOv11 Large'), ('yolo11x.pt', 'YOLOv11 XLarge')], default='yolo11s.pt', help_text='Modelo YOLOv11 a utilizar para detección', max_length=20),
        ),
        migrations.AlterField(
            model_name='modeloconfig',
            name='classes',
            field=models.CharField(default='0', help_text='Clases a detectar según COCO.yaml. 0 para personas', max_length=100),
        ),
        migrations.AlterField(
            model_name='modeloconfig',
            name='confidence_threshold',
            field=models.FloatField(default=0.25, help_text='Umbral de confianza para la detección'),
        ),
        migrations.AlterField(
            model_name='modeloconfig',
            name='device',
            field=models.CharField(choices=[('cpu', 'CPU'), ('cuda', 'CUDA')], default='cuda', max_length=20),
        ),
        migrations.AlterField(
            model_name='modeloconfig',
            name='image_size',
            field=models.IntegerField(default=640, help_text='Tamaño de entrada de la imagen (por ejemplo 640)'),
        ),
        migrations.AlterField(
            model_name='modeloconfig',
            name='stride',
            field=models.IntegerField(default=1, help_text='Número de frames a saltar'),
        ),
        migrations.AlterField(
            model_name='trackingconfig',
            name='distance_threshold',
            field=models.FloatField(default=35.0, help_text='Distancia máxima para asociar detecciones'),
        ),
        migrations.AlterField(
            model_name='trackingconfig',
            name='dwell_time_threshold',
            field=models.FloatField(default=5.0, help_text='Tiempo mínimo de permanencia (segundos)'),
        ),
    ]
